---
- hosts: localhost
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml
        # - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  # handlers:
  #   - name: Include handlers
  #     ansible.builtin.import_tasks: tasks/handlers.yml
  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml
      when: docker == true
    - name: Setup Tooling.
      ansible.builtin.import_tasks: tasks/setup.yml
      when: setup == true